// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mirczsithzxnimgxqjkl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1pcmN6c2l0aHp4bmltZ3hxamtsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5Mzc0ODMsImV4cCI6MjA2OTUxMzQ4M30.3Y5w4valAGo5-NxV9amDXeWXwv-yQG793bMdnYSr8uw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});